
  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    env_file:
    - ../.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql